### ISSUE TITLE
One-time update parameters

### ISSUE THREAD

**Issue by ajnisbet** [odojs/odo-relay#1]
Currently, any params that are passed to `update()` are remembered for future updates. This seems like state to me.

It would be nice to have params that don't get remembered,  so you could to something like

``` coffeescript
scene.update(doSomeTask: true)
```

without having to add

``` coffeescript
scene.update(doSomeTask: false)
```

to every single other `scene.update()` in your app.

**Comment by tcoats** [comment]
Params are remembered so child views can change while everything needed for the parent view remains.

For example this timeline of events:
1. params for parent view
2. parent view query
3. event selecting a piece of data in parent view
4. params for parent view and child view
5. child view query

My suggestion is to support clearing an individual property so if you really do want to remove a value you can.
e.g. `scene.remove('doSomeTask')`

Thoughts?

This addition won't solve the issue of wanting a transient property in the params. For that I suggest using hub events directly to the component (if it's a widget).

**Comment by ajnisbet** [comment]
If you did a remove function, you'd also want `scene.add('doSomeTask', 'task1')`

Do you ever need to change the scene params without an update? You can already do `scene.update(doSomeTask: undefined)`. Maybe if you want to change params, knowing that scene.update is about to be called soon anyway.

**Comment by tcoats** [comment]
`scene.update(doSomeTask: undefined)` is probably good enough then I guess.
It's unlikely you want to change params without kicking off an update.

**Comment by tcoats** [comment]
Are you happy enough that odojs remembers params, or do you think transient parameters would be a valuable addition?

**Comment by ajnisbet** [comment]
Now that I've got my head around state vs. params, I think things are fine as they are.

Widgets that need transient parameters can use events, odo-hub, or track state/params changes internally.

Also, I gather calls to `scene.update(params)` are guaranteed to update params, but are not guaranteed to be rendered (if another call is made shortly after)? Then adding transient parameters would be a non-trivial change. I say leave it unless it becomes a big issue.
